### ISSUE TITLE
the computing process of min_mse,min_mae,min_mape？

### ISSUE THREAD

**Issue by plaxkk** [VeritasYin/STGCN_IJCAI-18#12]
I want to know the reason of the computing process of min_mse,min_mae,min_mape？

**Comment by plaxkk** [comment]
btw,when the actual value almost equals zeros ,it's not suitable to use mape for calculating the error.Or,you preprocess the data in case of being zeros?

**Comment by VeritasYin** [comment]
1) We use the performance on the validation set to guide the model to update metrics of test set.
2) As we mentioned in the paper, "The linear interpolation method is used to fill missing values after data cleaning. In addition, data input are normalized by Z-Score method."
