### ISSUE TITLE
Dataset cannot be downloaded

### ISSUE THREAD

**Issue by hondaathma** [VeritasYin/STGCN_IJCAI-18#15]
![image](https://user-images.githubusercontent.com/26149657/53043846-47e02780-343e-11e9-90af-94c0d512c1bb.png)

Hi there is no option for Time Period . Hence all we have is a list of txt for each month in available files:

![image](https://user-images.githubusercontent.com/26149657/53044049-c76df680-343e-11e9-930c-5ae753c2d854.png)

**Comment by VeritasYin** [comment]
Hi,
Sorry for the late reply.
In the first screenshot you attached, you can find a calendar box just below "D7 2012 Station 5-Minute". The left index represents for the year and the following  gray rectangle denotes the corresponding month. You can click those gray boxes for certain time periods.
Thank you
