### ISSUE TITLE
Dimensions of the Input Dataset

### ISSUE THREAD

**Issue by pratikvpatil** [VeritasYin/STGCN_IJCAI-18#16]
Hi, 
I was having troble downloading and interpreting the dataset form PEMS, can you please let us know what is the dimension of the Input dataset, or please let me know if my interpretation is correct:

**PeMSD7_W_228.csv:** It is a weighted adjacency matrix of the graph with nodes n, size = n*n
**PeMSD7_V_228.csv:** It has time series data for every node in graph,  size =n*T , where T is len of time series.

**Comment by VeritasYin** [comment]
Hi,

As described in README,
"You can make your customized dataset by the following format:
PeMSD7_V_{%num_route%}.csv : Historical Speed Records with shape of [len_seq * num_road] (len_seq = day_slot * num_dates).
PeMSD7_W_{%num_route%}.csv : Weighted Adjacency Matrix with shape of [num_road * num_road].
Note: please replace the %num_route% with the number of routes in your dataset. '*.csv' should not contain any index or header in the file."

Thank you
