### ISSUE TITLE
Dataset upload

### ISSUE THREAD

**Issue by Lorrainexun** [VeritasYin/STGCN_IJCAI-18#18]
Hi we are very interested in your paper, can you open source your dataset?

Thanks a lot!

**Comment by VeritasYin** [comment]
Hi, thank you for your interest in our research.

As for the dataset, please refer to Issue #6 and README. We also plan to release the processed PeMS-M by the first quarter of this year. 

Thank you for your patience.

**Comment by sam101340** [comment]
@VeritasYin 
Hi,VeritasYin 
     Thank you very much for your answer.I would like to ask: When you calculating the weighted adjacency matrix , you based on "the distances among stations". I would like to ask you which indicator in the downloaded data is the distance between the stations. Is it "Station Length"? I also want to ask how to choose the Station ID.
Thanks a lot!

**Comment by VeritasYin** [comment]
Hi @sam101340,
Sorry for my late reply.

As for the distance between stations, you can obtain the meta data from PeMS website. I will also upload a pre-calculated adjacent matrix later this week. Thank you for your understanding and patience.

As for metadata of sensor stations, please visit the PeMS website first, and then select Clearinghouse section (lower left corner). At that webpage, you can choose 'station metadata' and 'district 7' to get the info at the lower right box named  'Available Files'. [[Link](http://pems.dot.ca.gov/?dnode=Clearinghouse&type=meta&district_id=7&submit=Submit)]

Thank you, ht

**Comment by arianprabowo** [comment]
Hi @VeritasYin ,

How do you calculate the distance between the stations? Is it distance through the road network, or "as the crow flies"?

Do you have the list of the ID of the 228 and 1,026 stations? So we can know which stations you use.

How to find out the connectivity between stations?

Thank you,
AP

**Comment by Mayaohong** [comment]
Hi, I see in you give others said in reply to upload a pre-calculated adjacent matrix file, I didn't find in this web site, https://github.com/VeritasYin/STGCN_IJCAI-18, The data that has been publicly available cannot be used to construct adjacent matrix. How can I obtain adjacent matrix files? Thank you
