### ISSUE TITLE
Question on Baseline Models

### ISSUE THREAD

**Issue by prateikarora** [VeritasYin/STGCN_IJCAI-18#19]
In the baseline models that you implemented(HA, ARIMA, LSVR, etc.); were they trained solely on the temporal data or the entire spatio-temporal data?

**Comment by VeritasYin** [comment]
As for details of baseline models, please refer to the [paper](https://www.ijcai.org/proceedings/2018/0505.pdf) and corresponding references. Traditional models normally are not able to handle spatio-temporal graphs. However, we trained separate models under the same framework for each road in the traffic network.

Thank you
