### ISSUE TITLE
How can I get the road network data

### ISSUE THREAD

**Issue by caoh18** [VeritasYin/STGCN_IJCAI-18#21]
Hello,
    I'd like to know how can I get the road topology network from PeMS dataset. Or did you build the network yourself? Besides, What the difference between the "station" and "link" in PeMS dataset? Thank you!

**Comment by VeritasYin** [comment]
In our experiment, we did not explicitly use the topology of road network. Instead, we use Eq. 10 to construct the adjacent matrix in our paper. And you can download the metadata of stations (not link) from pems.dot.ca.gov
