### ISSUE TITLE
About data partitioning

### ISSUE THREAD

**Issue by ZGX010** [VeritasYin/STGCN_IJCAI-18#22]
I noticed that you divided the data into training validation and test sets, and I found that the data provided in your code can be divided into 44 days by 288, and the number of days in the original data should be 61 days. Can you put the test and validation sets in? thank you very much.

**Comment by GreatWizard9519** [comment]
> I noticed that you divided the data into training validation and test sets, and I found that the data provided in your code can be divided into 44 days by 288, and the number of days in the original data should be 61 days. Can you put the test and validation sets in? thank you very much.

Please note that the data is collected from only weekdays of May and June 2012, say 44 days in total.
