### ISSUE TITLE
How to generate the W file?

### ISSUE THREAD

**Issue by arianprabowo** [VeritasYin/STGCN_IJCAI-18#24]
Hi @VeritasYin ,

How do you calculate the distance between the stations? Is it distance through the road network, or "as the crow flies"?

Do you have the list of the ID of the 228 and 1,026 stations? So we can know which stations you use.

How to find out the connectivity between stations?

Thank you,
AP

_Originally posted by @arianprabowo in https://github.com/VeritasYin/STGCN_IJCAI-18/issues/18#issuecomment-496757351_

**Comment by VeritasYin** [comment]
We use the Euclidian distance between two pairs of stations. And we also provide with the weighted adjacent matrix for your reference.

For details of the connectivity or  topology of stations, please refer to the metadata (pems.dot.ca.gov).
