### ISSUE TITLE
Issue on the Normalization Trick.

### ISSUE THREAD

**Issue by CHELSEA234** [VeritasYin/STGCN_IJCAI-18#25]
Hi, I think your code is very organized and neat, I really like it.

However, I have some questions about your code regarding the graph kernel generation. This is the [link](https://github.com/tkipf/gcn/issues/20#issuecomment-354660084) about how to do the normalization on the Laplacian matrix. In particular, we have to obtain symmetrically normalized laplacian formatted as follow.
![Screen Shot 2019-06-04 at 3 45 35 PM](https://user-images.githubusercontent.com/24967323/58918703-3ca8c300-86e0-11e9-982b-dfc991535101.png)

In contrast, your code goes like this:
```
    for i in range(n):
        for j in range(n):
            if (d[i] > 0) and (d[j] > 0):
                L[i, j] = L[i, j] / np.sqrt(d[i] * d[j])
```

Can you tell me what your idea about this?

**Comment by VeritasYin** [comment]
We use the same way to generate the normalized Laplacian as you referred to. But we skipped all zero entries in the matrix, 'd' is the diagonal degree matrix of 'W' and 'L = -W'.
