### ISSUE TITLE
Why does the adjacency matrix for PEMS-M only have 32 value greater 0?

### ISSUE THREAD

**Issue by Felijasha** [VeritasYin/STGCN_IJCAI-18#27]
Hello :)
I'm trying to implement the PEMS-M dataset for my models which is similar to your model.
I had a look at the adjacency matrix and I have notices that there are only 32 values greater 0.
I think that is too little for 228 nodes.
Maybe I just have missed some information.
Thank you in advance for your reply.

Best wishes!

**Comment by ahariri13** [comment]
@Felijasha Could you please elaborate on this ? I was wondering the same thing

**Comment by Felijasha** [comment]
I found out, that the graph has 1664 edges. That's close to the amount of edges in the METR-LA dataset with 207 instead of 228 nodes. So the weight matrix should be okay.

**Comment by ahariri13** [comment]
@Felijasha In case you're still up-to-date in this, may I ask you about the significance of the lines below ? (lines 71 and 72) in trainer.py, especially when it comes to the significance of the three values 4e1,1e5,1e5 in the inference process. Thanks in advance :)

step_idx = tmp_idx = np.arange(3, n_pred + 1, 3) - 1
min_val = min_va_val = np.array([4e1, 1e5, 1e5] * len(step_idx))

**Comment by Felijasha** [comment]
Sorry in this issue I can't really help you.
I'm writing actual my bachelor thesis and I'm using the STGCN framework for my model in the thesis. I use another implementation as fundamental. I will have a look at it in the following days. Maybe I have an idea.

**Comment by yaoqi-zd** [comment]
> I found out, that the graph has 1664 edges. That's close to the amount of edges in the METR-LA dataset with 207 instead of 228 nodes. So the weight matrix should be okay.

@Felijasha Hi, I have the same question. the adjacent matrix only has 30+ values greater than 0, means the graph only has 30+ edges, which is too little for 228 nodes. what do you mean by 'the graph has 1664 edges' ?
