### ISSUE TITLE
Tips for using repo in colab

### ISSUE THREAD

**Issue by gg4u** [VeritasYin/STGCN_IJCAI-18#32]
Hi, I read your paper, my background is not mathematics but I could follow the main reasoning.

I would like to use the git to better understand the steps described in the paper, and then to try apply on my own datasets for learning purposes.

I tried cloning the git on colab, run python main.py as test:

```
Training configs: Namespace(batch_size=50, epoch=50, graph='default', inf_mode='merge', ks=3, kt=3, lr=0.001, n_his=12, n_pred=9, n_route=228, opt='RMSProp', save=10)
ERROR: input file was not found in ./dataset/PeMSD7_W_228.csv.
Traceback (most recent call last):
  File "main.py", line 51, in <module>
    W = weight_matrix(pjoin('./dataset', f'PeMSD7_W_{n}.csv'))
  File "/content/STGCN_IJCAI-18/utils/math_graph.py", line 86, in weight_matrix
    if set(np.unique(W)) == {0, 1}:
UnboundLocalError: local variable 'W' referenced before assignment
```

Do you have time to provide for a documentation ?

If guided step by step, I am also willing to refactor code for jupyter / colab environment.
It will be a learning experience for me to structure a GNC model, and I think useful for others too.

I am also interested in using DGL - begineer, but it seems a tool purposufully designed for this types of models.

Please have a look:
https://github.com/dmlc/dgl

**Comment by VeritasYin** [comment]
Please refer to README.md for the format of customized dataset. 

And the output you provided with indicated that the adjacent matrix is missing.
