### ISSUE TITLE
Computing Weighted Adjacency Matrix and replicate results

### ISSUE THREAD

**Issue by gg4u** [VeritasYin/STGCN_IJCAI-18#33]
Hello Haoteng,

thank you for sharing the code for your paper, which I am studying:

I understood the big picture, and given the level of my mathematical background, I want to help myself with code step by step for a deeper understanding.

As first thing, I would like to be able run your code, and replicate results.

Could you please go through your code and point out the main functions to replicate results in your paper ?

I am using Colab virtual environment, I downloaded dataset from :
http://pems.dot.ca.gov

to be clear, they are this kind of files:
`d07_text_station_5min_2019_01_02.txt.gz`

which is in the form of :

```
['05/27/2012 00:00:00' 715898 7 5 'S' 'ML' 0.43 0 0 245.0 0.096 54.3 0
  86.0 0.0794 60.6 0 0.0 92.0 0.0852 53.0 0 0.0 67.0 0.1233 48.2 0 nan
  nan nan nan 0 nan nan nan nan 0 nan nan nan nan 0 nan nan nan nan 0 nan
  nan nan nan 0] ...  ]
````

Can you tell how do you manipulate them to format raw data as: 
```
PeMSD7_V_{%num_route%}.csv : Historical Speed Records with shape of [len_seq * num_road] (len_seq = day_slot * num_dates).
PeMSD7_W_{%num_route%}.csv :
```

If I run a plain `python main.py` it will yield error, for it is not the W matrix that it is expecting. How to compute W from raw data? Should it be pre-processed separately or is it handled in your code somewhere ?

Possible to provide a quick reference for the code? 

Thank you!

**Comment by VeritasYin** [comment]
1) The data should be preprocessed as time-series. For each station of the traffic network, it is a node of the graph in our model. For details, please refer to our paper in section 4.1 & 4.2;
2) The adjacency matrix is generated based on Eq. 10;
3) For better understanding code, I suggest that you might start from some basic framework such as GCN (Ref: https://github.com/tkipf/gcn).
