### ISSUE TITLE
hi , could you please explain how did you form the vertex and weight matrix from the data ( which nodes did you choose ?  etc . )

### ISSUE THREAD

**Issue by coolcoder001** [VeritasYin/STGCN_IJCAI-18#34]
Hi @VeritasYin , could you please inform how did you form the vertex and weight matrix csvs from the available files ?

I can find so many files to download.

**Comment by VeritasYin** [comment]
You can refer to https://github.com/VeritasYin/STGCN_IJCAI-18/issues/6#issuecomment-448533605 and https://github.com/VeritasYin/STGCN_IJCAI-18/issues/18#issuecomment-490960463.
Also, we construct the adjacency matrix based on Eq. 10 in our paper.
