### ISSUE TITLE
Whether the BJER4 dataset and PeMS(L)dataset is openned?

### ISSUE THREAD

**Issue by Xieyyyy** [VeritasYin/STGCN_IJCAI-18#35]
Hello, Yin:
I'm can not find BJER4 dataset and I don't know how to construct PeMS(L) dataset, whether both datasets is openned?

**Comment by VeritasYin** [comment]
Hi,
Unfortunately, as for the BJER4, it is a private dataset which is restricted by a confidentiality agreement. Therefore, we are not able to release in public. However, as for the PeMS, you can directly download the data from the official website (http://pems.dot.ca.gov/). And we will release the full list of station ID of PeMSD7-L in the near future.
