### ISSUE TITLE
About the S-T blocks.

### ISSUE THREAD

**Issue by JCwww** [VeritasYin/STGCN_IJCAI-18#36]
Hi there, 
May I ask why the S-T blocks are the so-called sandwich structure? 
What is the strategy or reason of this?
Thanks!

**Comment by VeritasYin** [comment]
We named the ST-blocks as a sandwich structure mainly based on the channel alteration and bottleneck stargery applied in those blocks. As we described in the paper, we first reduce the number of channels from the top temporal layer to the middle spatial one, then expand the channels from the middle layer to the bottom temporal one.
