### ISSUE TITLE
Asking for the sensor location for PeMSD7-M

### ISSUE THREAD

**Issue by xlwang233** [VeritasYin/STGCN_IJCAI-18#38]
Hello Yin,

Thank you for releasing your source code and dataset! It helped me a lot on my own research project!
 But in this repo you only uploaded the speed series data and the graph weight matrix. Could you please generously release the geographical location (latitude&longitude) of sensors in **PeMSD7-M**? or the list of sensor IDs so that I can visualize them on the map. 
I also checked other closed issues in which you said you will release the full list of station ID of PeMSD7-L soon.

I'm very looking forward to your update!

Thanks in advance

**Comment by wubin5** [comment]
你好，我也想获得pemsD7的传感器ID和地理位置分布，方便分享吗。后期论文会引用您的文章。

**Comment by VeritasYin** [comment]
The station list is now available under the dataset folder.
