### ISSUE TITLE
STGCN(Cheb) and STGCN(1st)

### ISSUE THREAD

**Issue by SYSUHPK** [VeritasYin/STGCN_IJCAI-18#46]
Hello, I wonder whether the source code is about STGCN(Cheb)? How can I get STGCN(1st)? Ks = Kt =2?
And in your paper, you say"the channels of three layers in ST-Conv block are 64, 16, 64 respectively. ", but it seems that it is [1,32,64][64,32,128] in your source code?

**Comment by VeritasYin** [comment]
You can use the function first_approx(W, n) defined in utils/math_graph.py to replace cheb_poly_approx(L, Ks, n).

**Comment by michealowen** [comment]
> You can use the function first_approx(W, n) defined in utils/math_graph.py to replace cheb_poly_approx(L, Ks, n).

When change to first_approx(W, n), an error occurs. Have u ever noticed that?
