### ISSUE TITLE
About adjacency matrix

### ISSUE THREAD

**Issue by SYSUHPK** [VeritasYin/STGCN_IJCAI-18#47]
Hello, I read your paper and was cofused by the dataset PeMSD7's adjacency matrix. 
Accoring to the formula:
![image](https://user-images.githubusercontent.com/47689665/88446280-3ed95e00-ce5b-11ea-9063-e62194bae7ac.png)
And the W_ss8.csv:
![image](https://user-images.githubusercontent.com/47689665/88446443-801e3d80-ce5c-11ea-8bd6-409fc46afb53.png)
I found that most of wij is a*10^3, for example, the matrix[0,1]=3165.94, let 3165.94 = exp(-dij^2/δ^2)，it seems that it is impossible. What is the matter?

**Comment by VeritasYin** [comment]
Hi, I'm not sure where does this file 'W_ss8.csv' you referred come from. Before computing the weighted adjacency matrix, please pay attention to the metric of $d_{ij}$, that is whether it is in km or meter.
