### ISSUE TITLE
About first_approx()

### ISSUE THREAD

**Issue by aptx1231** [VeritasYin/STGCN_IJCAI-18#51]
In the function `def first_approx(W, n):`，
Why do you use `np.mat(np.identity(n) + sinvD * A * sinvD)` as a result?
Refer to the Eq.5, I think there should not add `np.identity(n)`，because the matrix A has already add the identity matrix in `A = W + np.identity(n)` 。
Looking forward to your reply，Thank you.

**Comment by VeritasYin** [comment]
Please refer to [SEMI-SUPERVISED CLASSIFICATION WITH GRAPH CONVOLUTIONAL NETWORKS](https://arxiv.org/pdf/1609.02907.pdf).

**Comment by aptx1231** [comment]
> Please refer to [SEMI-SUPERVISED CLASSIFICATION WITH GRAPH CONVOLUTIONAL NETWORKS](https://arxiv.org/pdf/1609.02907.pdf).

In this paper section2.2，he uses I_{N}+D^{-1/2}AD^{-1/2} --> D~^{-1/2}A~D~^{-1/2}。
In your code A is his A~，but you add a I_{N}。

**Comment by aptx1231** [comment]
The section2.2:
[paper](https://ftp.bmp.ovh/imgs/2021/03/588b394487505089.png)

**Comment by VeritasYin** [comment]
In this implementation, the diagonal of loaded W is all 0s. We added self loops to maintain the numerical stability. The rest is the same.
