### ISSUE TITLE
adjacency matrix computation and its heatmap

### ISSUE THREAD

**Issue by csyanghan** [VeritasYin/STGCN_IJCAI-18#56]
As shown in the below figure:
![image](https://user-images.githubusercontent.com/31543505/125804875-b53811f4-0773-4571-8018-cb76a886a02e.png)
we know that $w_{ij}=0$ for i==j, but in the heatmap it can be seen that $w_{ij}>=0.5$
and from the Eq.10, $w_{ij}=1$ for $i!=j$ and d_ij = 0, and i think it's not unreasonable.
Hope for you reply, thanks!

**Comment by VeritasYin** [comment]
The diagonal of W is all zeros. The heat map is for the purpose of illustration, which only differentiate  the value between 0.5 and 1.0.

**Comment by csyanghan** [comment]
> The diagonal of W is all zeros. The heat map is for the purpose of illustration, which only differentiate the value between 0.5 and 1.0.

what about w_ij=1 if d_ij=0 and i != j , can you explain more specifically.

**Comment by VeritasYin** [comment]
If d_{ij} = 0, it means there is no connection (edge) between node i and node j. Accordingly, it should not assign any weights in this case. Eq 10 only should be applied to d_{ij} > 0.

**Comment by csyanghan** [comment]
> If d_{ij} = 0, it means there is no connection (edge) between node i and node j. Accordingly, it should not assign any weights in this case. Eq 10 only should be applied to d_{ij} > 0.

Thanks, I got it.
