### ISSUE TITLE
what purpose of this model

### ISSUE THREAD

**Issue by nanhui69** [VeritasYin/STGCN_IJCAI-18#58]
in this tf repo ,what usage for this model？ is it suits for action recognition? who can explain it .....

**Comment by VeritasYin** [comment]
This model is used for traffic prediction through spatio-temporal time series. For action recognition, you might refer to [Spatial Temporal Graph Convolutional Networks for Skeleton-Based Action Recognition](https://arxiv.org/abs/1801.07455).
