### ISSUE TITLE
How to download the dataset from PeMS website?

### ISSUE THREAD

**Issue by zwd2016** [VeritasYin/STGCN_IJCAI-18#6]
Hi, VeritasYin:
       I really got impressed by this paper (STGCN-IJCAI-18). But there is no dataset in your code, and the PeMSD7 link is not very clear what data needs to be exported as a dataset.  I'm hoping to get your help. Thank you very much for your help and looking forward to your reply.
Have a nice day!

Regards,
Wendong

**Comment by VeritasYin** [comment]
Hey,

Thank you for your interest in our study. After you log into the PeMS website, please visit the link http://pems.dot.ca.gov/?dnode=Clearinghouse. Using following parameters to locate the dataset: 
Type: Station 5-minute; 
District: 7; 
Time Period: Weekdays of May and June of 2012. 

If everything is all right, please select 'D7 2012 Station 5-Minute' in the dashboard. Then you are able to find the requested data in the section of 'Available Files'.

Cheers, ht

**Comment by zwd2016** [comment]
Hi,
Thank you very much!
Regards,
wendong

**Comment by sam101340** [comment]
Hi VeritasYin:
Thank you very much! But I can`t find the 'Time Period' in the http://pems.dot.ca.gov/?dnode=Clearinghouse.How to solve?

**Comment by prateikarora** [comment]
@sam101340 in the calendar like box, click the small gray rectangle for the corresponding month and year

**Comment by sam101340** [comment]
@VeritasYin 
Hi,VeritasYin
Thank you very much for your answer.I would like to ask: When you calculating the weighted adjacency matrix , you based on "the distances among stations". I would like to ask you which indicator in the downloaded data is the distance between the stations. Is it "Station Length"? I also want to ask how to choose the Station ID.
Thanks a lot!

**Comment by CHELSEA234** [comment]
@sam101340 
I think you have raised a good question. I also want to reproduce the results, the data so will be very important. Have you figured out how to construct the adjacent matrix yet?

**Comment by steven1536796418** [comment]
@zwd2016 
你好，请问这个工程是如何运行的呢？对于我这个新手来说简直是盲人过河，如果你能指点一二，万分感谢。
Hi, I want to ask a relatively low-level question, how does this project work? This seems like a easy question, but I am the green hands. Thank you very much!

**Comment by steven1536796418** [comment]
@CHELSEA234  
你好，请问这个工程是如何运行的呢？对于我这个新手来说简直是盲人过河，如果你能指点一二，万分感谢。
Hi, I want to ask a relatively low-level question, how does this project work? This seems like a easy question, but I am the green hands. Thank you very much!

**Comment by steven1536796418** [comment]
@CHELSEA234 @sam101340 
When I operate the main.py in cmd, it occurred the fault that "local variable 'W' referenced before assignment", may you explain it for me, thank you very much!

**Comment by steven1536796418** [comment]
@VeritasYin 
Hi, I am interested in your study, and I think the graph convolutional network applied in the traffic prediction is an innovative idea.

**Comment by xumingxingsjtu** [comment]
> Hi,
> Thank you very much!
> Regards,
> wendong

Hello! I am also interested in this work and want to reproduce it, but I can not download the datasets. Have you already downloaded the datasets? Would you mind share the datasets to me? 
Thank you very much!

**Comment by VeritasYin** [comment]
@sam101340 @CHELSEA234 @xumingxingsjtu 
Sorry for my late reply.

As for construction of the adjacent matrix, please refer to issue #18. The PeMS dataset and weighted adjacent matrix will be ready to release by end of this week. Thank you for your understanding and patience.

Regards, ht

**Comment by xiepeng21** [comment]
Hello, I can't access the website "http://pems.dot.ca.gov/" to download the datasets, Does it can't work recently? If not, could you share the datasets for me?  My email is xiepeng21@foxmail.com.
Thank you.

**Comment by VeritasYin** [comment]
Hi @xiepeng21 
So far, the PeMS website is accessible. You may try to visit it with the proxy tool. But sometimes it could be difficult. We will also release the PeMS dataset later this week. 
Thanks, ht

**Comment by FelixOpolka** [comment]
Hi @VeritasYin Thank you for publishing the code for STGCN. Has there been any updates concerning the release of the PeMS dataset?

**Comment by xumingxingsjtu** [comment]
Hello! @VeritasYin  I am reproducing the results of your paper, and I wander if you could share your baseline code HA, LSVR,ARIMA,FNN,FC-LSTM with me?

**Comment by coolcoder001** [comment]
Hi @VeritasYin , could you please inform how did you form the vertex and weight matrix csvs from the available files ?

I can find so many files to download.

**Comment by AimanMunir24** [comment]
How can we know which sensors are on the same road? What is difference between freeway and road?

**Comment by Daishijun** [comment]
Hi, I am interested in your study. I wonder how to choose the Station ID. There are so many Station IDs, but how can I know where is the station xxx?

**Comment by VeritasYin** [comment]
For the details of sensor stations, please refer to the metadata from PeMS website. It provides the following key values, 

- ID | An integer value that uniquely indenties the Station Metadata. Use this value to 'join' other clearinghouse files that contain Station Metadata
- Freeway | Freeway Number
- Latitude | Latitude. 
- Longitude | Longitude.

@AimanMunir24 @Daishijun

**Comment by razvanc92** [comment]
@VeritasYin Could you please share the sensors ids you used? We need a mapping from the adj matrix you released to the sensors ids from the website.

**Comment by sanaz20** [comment]
How can I download a road congestion dataset for 5 years from PeMS?

**Comment by tinmodeHuang** [comment]
> Hi @xiepeng21
> So far, the PeMS website is accessible. You may try to visit it with the proxy tool. But sometimes it could be difficult. We will also release the PeMS dataset later this week.
> Thanks, ht

wow! it is concluded alone from questions and timely reply in the issue that you're a nice guy and walk everyone through the code like babysitting. I suppose I could go through the code faster than I did one.

**Comment by hugh2009hugh** [comment]
mark

**Comment by sanaz20** [comment]
Hi, how can I find weather and accident data on Pems website?

**Comment by parvin-ahmadi** [comment]
Hi, How can I merge the dataset with weather data? can I download a dataset that is a combination of traffic and weather data by PeMS?

**Comment by parvin-ahmadi** [comment]
Hi, How can I merge the dataset with weather data? can I download a dataset that is a combination of traffic and weather data on PeMS?

**Comment by AdnanQaseem** [comment]
could you please send the link for download the datasets, thank you

**Comment by Sigma9955** [comment]
could you please send the link for download the datasets

**Comment by steven1536796418** [comment]
感谢你的来信，我已经收到了。Thank you for your email，I have received it.

**Comment by MaheshBhalavi** [comment]
> Hi @xiepeng21 So far, the PeMS website is accessible. You may try to visit it with the proxy tool. But sometimes it could be difficult. We will also release the PeMS dataset later this week. Thanks, ht



> Hey,
> 
> Thank you for your interest in our study. After you log into the PeMS website, please visit the link http://pems.dot.ca.gov/?dnode=Clearinghouse. Using following parameters to locate the dataset: Type: Station 5-minute; District: 7; Time Period: Weekdays of May and June of 2012.
> 
> If everything is all right, please select 'D7 2012 Station 5-Minute' in the dashboard. Then you are able to find the requested data in the section of 'Available Files'.
> 
> Cheers, ht

Hello Sir My name is Mahesh Bhalavi 
I m doing study on Traffic Path Recommendations System and find your work very interesting and referring your work for that.
For the same reason i want PeMSD 7 dataset and i m finding it difficult to download. I m reached till Available Files section as you mention in above message. From there i m finding difficult to procced as there are many metadata files from may 2012 to june 2012. I m eagerly awaiting for you help sir.


Thank You Sir

**Comment by steven1536796418** [comment]
感谢你的来信，我已经收到了。Thank you for your email，I have received it.

**Comment by WissamFER** [comment]
Hello, very interresting work , someone can share with me the dataset please i'am traying to undestand the code . 
my mail: wissamsawsan1999@gmail.com

**Comment by steven1536796418** [comment]
感谢你的来信，我已经收到了。Thank you for your email，I have received it.

**Comment by Bondify** [comment]
hi, this is a very interesting paper. Could someone please send the data to santiagoa.toso@gmail.com? I would like to follow the notebook and reproduce the code.
Thank you :)

**Comment by steven1536796418** [comment]
感谢你的来信，我已经收到了。Thank you for your email，I have received it.

**Comment by jisoo0-0** [comment]
I found there are so many available files in PeMS(Statio 5-min , district7).. Which one did you used in ur paper?

**Comment by twythebest** [comment]
about the dataset :how many files need to be downloaded?the dataset is one day form,so do i need to download all?

**Comment by steven1536796418** [comment]
感谢你的来信，我已经收到了。Thank you for your email，I have received it.

**Comment by laibajiu** [comment]
> 有关传感器站的详细信息，请参阅 PeMS 网站的元数据。它提供以下关键值：
> 
> * ID | 唯一标识站点元数据的整数值。使用此值“加入”包含站点元数据的其他信息交换所文件
> * 高速公路 | 高速公路号码
> * 纬度|纬度。
> * 经度|经度。
> 
> @AimanMunir24 @Daishijun
Hi, can you provide where to view the metadata, I can't find him on the official website, thanks a lot!

**Comment by steven1536796418** [comment]
感谢你的来信，我已经收到了。Thank you for your email，I have received it.

**Comment by laibajiu** [comment]
> Hi, can you provide where to view the metadata, I can't find him on the official website, thanks a lot!

Hi, can you provide where to view the metadata, I can't find him on the official website, thanks a lot!
