### ISSUE TITLE
where is your paper ''The temporal convolution layer maps outputs of the last ST-Conv block to a single-step prediction'?

### ISSUE THREAD

**Issue by plaxkk** [VeritasYin/STGCN_IJCAI-18#9]
I cannot find it on the internet

**Comment by VeritasYin** [comment]
Referring to my last reply, we pointed out that our model uses iterative single-step predictions to tackle the multi-step prediction task. The sentence you mentioned is cited from our paper 'STGCN', page 4, right column, line 6.

**Comment by plaxkk** [comment]
ok,I misunderstand your words，thx
